### ISSUE TITLE
Unable to run unit tests in Example Use Cases.ipynb

### ISSUE THREAD

**Issue by djinnome** [bel2scm/bel2scm#7]
Hi @cbakker2 

 I was trying to run the unit tests in [Example Use Cases.ipynb](https://github.com/bel2scm/bel2scm/blob/updated_code_craig/Example%20Use%20Cases.ipynb) but when I try to initialize any `str_graph`:

```python
graph_test = cg.str_graph(str_list=str_list,graph_type='SCM',type_dict=type_dict)
```

I get an error telling me that the `graph_type` parameter does not exist.  
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-48b2ae657d5a> in <module>
      7 type_dict['rainy'] = 'continuous'
      8 type_dict['icream'] = 'continuous'
----> 9 graph_test = cg.str_graph(str_list=str_list,graph_type='SCM',type_dict=type_dict)
     10 graph_test.add_confound([['icream','cloudy']])
     11 

TypeError: __init__() got an unexpected keyword argument 'graph_type'
```

Indeed, when I go to the `__init__` of `str_graph`, the only parameters are:

https://github.com/bel2scm/bel2scm/blob/4d3f693b37300e5042086a328db8eb6fa0d9f298/bel2scm/causal_graph.py#L1417-L1420

Please advise.

**Comment by cbakker2** [comment]
The causal graph code is now updated to accept the correct arguments.
